// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ThemarIP.Infrastructure.Persistence;

#nullable disable

namespace ThemarIP.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("ThemarIP.Domain.Entities.AiQuery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("QueryText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponseText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TokensUsed")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AiQueries");
                });

            modelBuilder.Entity("ThemarIP.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AdminUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReasonCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReasonNote")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TargetUserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AdminUserId");

                    b.HasIndex("TargetUserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("ThemarIP.Domain.Entities.CategoryRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Keyword")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("MccCode")
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Keyword");

                    b.ToTable("CategoryRules");
                });

            modelBuilder.Entity("ThemarIP.Domain.Entities.KycSubmission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentReferences")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReasonCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReasonNote")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ReviewedByAdminId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReviewedByAdminId");

                    b.HasIndex("UserId");

                    b.ToTable("KycSubmissions");
                });

            modelBuilder.Entity("ThemarIP.Domain.Entities.NboApiConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientSecret")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("NboApiConfigs");
                });

            modelBuilder.Entity("ThemarIP.Domain.Entities.Pfm.PfmAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AdminUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("NewValueJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("OldValueJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AdminUserId");

                    b.HasIndex("Timestamp");

                    b.HasIndex("EntityType", "EntityId");

                    b.ToTable("PfmAuditLogs", (string)null);
                });

            modelBuilder.Entity("ThemarIP.Domain.Entities.Pfm.PfmCategorizationRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Confidence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(85);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CreatedByAdminId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsLearnedFromCorrection")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<int>("MatchCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(50);

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Active");

                    b.Property<Guid?>("SubcategoryId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CreatedByAdminId");

                    b.HasIndex("IsLearnedFromCorrection");

                    b.HasIndex("Priority");

                    b.HasIndex("Status");

                    b.HasIndex("SubcategoryId");

                    b.ToTable("PfmCategorizationRules", (string)null);
                });

            modelBuilder.Entity("ThemarIP.Domain.Entities.Pfm.PfmCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("#94A3B8");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("Icon")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("tag");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DisplayOrder");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("PfmCategories", (string)null);
                });

            modelBuilder.Entity("ThemarIP.Domain.Entities.Pfm.PfmConfidenceBand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActionLabel")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("BandName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayLabel")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxThreshold")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(100);

                    b.Property<int>("MinThreshold")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BandName")
                        .IsUnique();

                    b.ToTable("PfmConfidenceBands", (string)null);
                });

            modelBuilder.Entity("ThemarIP.Domain.Entities.Pfm.PfmConfidenceWeight", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("#94A3B8");

                    b.Property<string>("DisplayLabel")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Signal")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("WeightPercent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("Signal")
                        .IsUnique();

                    b.ToTable("PfmConfidenceWeights", (string)null);
                });

            modelBuilder.Entity("ThemarIP.Domain.Entities.Pfm.PfmIntelligenceAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AlertText")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<Guid>("RuleId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TransactionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("TriggeredAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsRead");

                    b.HasIndex("RuleId");

                    b.HasIndex("TransactionId");

                    b.HasIndex("TriggeredAt");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "IsRead");

                    b.ToTable("PfmIntelligenceAlerts", (string)null);
                });

            modelBuilder.Entity("ThemarIP.Domain.Entities.Pfm.PfmIntelligenceRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("FireCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("Icon")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("zap");

                    b.Property<string>("IconColor")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("#3B82F6");

                    b.Property<string>("InsightTemplate")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastFiredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("RuleType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Active");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RuleType");

                    b.HasIndex("Status");

                    b.ToTable("PfmIntelligenceRules", (string)null);
                });

            modelBuilder.Entity("ThemarIP.Domain.Entities.Pfm.PfmIntelligenceRuleParam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ParamKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ParamType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("String");

                    b.Property<string>("ParamValue")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RuleId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RuleId", "ParamKey")
                        .IsUnique();

                    b.ToTable("PfmIntelligenceRuleParams", (string)null);
                });

            modelBuilder.Entity("ThemarIP.Domain.Entities.Pfm.PfmLearningSuggestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CurrentCategoryId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CurrentSubcategoryId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DetectedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("GeneratedRuleId")
                        .HasColumnType("TEXT");

                    b.Property<int>("OccurrenceCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Pending");

                    b.Property<Guid?>("SuggestedCategoryId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SuggestedConfidence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(85);

                    b.Property<Guid?>("SuggestedSubcategoryId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CurrentCategoryId");

                    b.HasIndex("CurrentSubcategoryId");

                    b.HasIndex("GeneratedRuleId");

                    b.HasIndex("OccurrenceCount");

                    b.HasIndex("Pattern");

                    b.HasIndex("Status");

                    b.HasIndex("SuggestedCategoryId");

                    b.HasIndex("SuggestedSubcategoryId");

                    b.ToTable("PfmLearningSuggestions", (string)null);
                });

            modelBuilder.Entity("ThemarIP.Domain.Entities.Pfm.PfmMerchant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CorrectionRate")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT")
                        .HasDefaultValue(0m);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DefaultCategoryId")
                        .HasColumnType("TEXT");

                    b.Property<int>("DefaultConfidence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(90);

                    b.Property<Guid?>("DefaultSubcategoryId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("MccCode")
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("TransactionCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DefaultCategoryId");

                    b.HasIndex("DefaultSubcategoryId");

                    b.HasIndex("IsActive");

                    b.HasIndex("MccCode");

                    b.HasIndex("Name");

                    b.ToTable("PfmMerchants", (string)null);
                });

            modelBuilder.Entity("ThemarIP.Domain.Entities.Pfm.PfmMerchantAlias", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AliasText")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MerchantId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AliasText")
                        .IsUnique();

                    b.HasIndex("MerchantId");

                    b.ToTable("PfmMerchantAliases", (string)null);
                });

            modelBuilder.Entity("ThemarIP.Domain.Entities.Pfm.PfmRuleCondition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LogicOperator")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("And");

                    b.Property<string>("Operator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderIndex")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<Guid>("RuleId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RuleId", "OrderIndex");

                    b.ToTable("PfmRuleConditions", (string)null);
                });

            modelBuilder.Entity("ThemarIP.Domain.Entities.Pfm.PfmSubcategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DisplayOrder");

                    b.HasIndex("CategoryId", "Name")
                        .IsUnique();

                    b.ToTable("PfmSubcategories", (string)null);
                });

            modelBuilder.Entity("ThemarIP.Domain.Entities.Pfm.PfmTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 3)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("BalanceAfter")
                        .HasPrecision(18, 3)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("OMR");

                    b.Property<bool>("IsEssential")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsRecurring")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("MccCode")
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("MerchantId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Narration")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Uncategorized");

                    b.Property<DateTimeOffset>("TransactionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MerchantId");

                    b.HasIndex("Status");

                    b.HasIndex("TransactionDate");

                    b.HasIndex("TransactionType");

                    b.HasIndex("UserId");

                    b.ToTable("PfmTransactions", (string)null);
                });

            modelBuilder.Entity("ThemarIP.Domain.Entities.Pfm.PfmTransactionCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CategorizedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Confidence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<Guid?>("MatchedRuleId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ScoreAmountPattern")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("ScoreHistoricalMatch")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("ScoreMccMatch")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("ScoreMerchantMatch")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("ScoreNarrationMatch")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("Source")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Uncategorized");

                    b.Property<Guid?>("SubcategoryId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Confidence");

                    b.HasIndex("MatchedRuleId");

                    b.HasIndex("Source");

                    b.HasIndex("SubcategoryId");

                    b.HasIndex("TransactionId")
                        .IsUnique();

                    b.ToTable("PfmTransactionCategories", (string)null);
                });

            modelBuilder.Entity("ThemarIP.Domain.Entities.Pfm.PfmUserCorrection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AdminNote")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CorrectedCategoryId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CorrectedSubcategoryId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CorrectionDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("GeneratedRuleId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OriginalCategoryId")
                        .HasColumnType("TEXT");

                    b.Property<int>("OriginalConfidence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<Guid?>("OriginalSubcategoryId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ReviewedByAdminId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Scope")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Pending");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CorrectedCategoryId");

                    b.HasIndex("CorrectedSubcategoryId");

                    b.HasIndex("CorrectionDate");

                    b.HasIndex("GeneratedRuleId");

                    b.HasIndex("OriginalCategoryId");

                    b.HasIndex("OriginalSubcategoryId");

                    b.HasIndex("ReviewedByAdminId");

                    b.HasIndex("Status");

                    b.HasIndex("TransactionId");

                    b.HasIndex("UserId");

                    b.ToTable("PfmUserCorrections", (string)null);
                });

            modelBuilder.Entity("ThemarIP.Domain.Entities.StatementUpload", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountNumber")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("DetectedBank")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Logs")
                        .HasColumnType("TEXT");

                    b.Property<long>("ProcessingDurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("FILE_UPLOAD");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ValidationWarnings")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("StatementUploads");
                });

            modelBuilder.Entity("ThemarIP.Domain.Entities.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("ThemarIP.Domain.Entities.SystemLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Exception")
                        .HasColumnType("TEXT");

                    b.Property<string>("LogLevel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SystemLogs");
                });

            modelBuilder.Entity("ThemarIP.Domain.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 3)
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MccCode")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("StatementUploadId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("TransactionDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UserId1")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StatementUploadId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId1");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("ThemarIP.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AccessReasonCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("AccessReasonNote")
                        .HasColumnType("TEXT");

                    b.Property<string>("AccessStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Pending");

                    b.Property<string>("AccountNumber")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TrustScore")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ThemarIP.Domain.Entities.AiQuery", b =>
                {
                    b.HasOne("ThemarIP.Domain.Entities.User", "User")
                        .WithMany("AiQueries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ThemarIP.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("ThemarIP.Domain.Entities.User", "AdminUser")
                        .WithMany("AdminAuditLogs")
                        .HasForeignKey("AdminUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ThemarIP.Domain.Entities.User", "TargetUser")
                        .WithMany("TargetAuditLogs")
                        .HasForeignKey("TargetUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdminUser");

                    b.Navigation("TargetUser");
                });

            modelBuilder.Entity("ThemarIP.Domain.Entities.KycSubmission", b =>
                {
                    b.HasOne("ThemarIP.Domain.Entities.User", "ReviewedByAdmin")
                        .WithMany()
                        .HasForeignKey("ReviewedByAdminId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ThemarIP.Domain.Entities.User", "User")
                        .WithMany("KycSubmissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReviewedByAdmin");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ThemarIP.Domain.Entities.Pfm.PfmAuditLog", b =>
                {
                    b.HasOne("ThemarIP.Domain.Entities.User", "AdminUser")
                        .WithMany()
                        .HasForeignKey("AdminUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AdminUser");
                });

            modelBuilder.Entity("ThemarIP.Domain.Entities.Pfm.PfmCategorizationRule", b =>
                {
                    b.HasOne("ThemarIP.Domain.Entities.Pfm.PfmCategory", "Category")
                        .WithMany("Rules")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ThemarIP.Domain.Entities.User", "CreatedByAdmin")
                        .WithMany()
                        .HasForeignKey("CreatedByAdminId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ThemarIP.Domain.Entities.Pfm.PfmSubcategory", "Subcategory")
                        .WithMany("Rules")
                        .HasForeignKey("SubcategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");

                    b.Navigation("CreatedByAdmin");

                    b.Navigation("Subcategory");
                });

            modelBuilder.Entity("ThemarIP.Domain.Entities.Pfm.PfmIntelligenceAlert", b =>
                {
                    b.HasOne("ThemarIP.Domain.Entities.Pfm.PfmIntelligenceRule", "Rule")
                        .WithMany("Alerts")
                        .HasForeignKey("RuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ThemarIP.Domain.Entities.Pfm.PfmTransaction", "Transaction")
                        .WithMany()
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ThemarIP.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rule");

                    b.Navigation("Transaction");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ThemarIP.Domain.Entities.Pfm.PfmIntelligenceRuleParam", b =>
                {
                    b.HasOne("ThemarIP.Domain.Entities.Pfm.PfmIntelligenceRule", "Rule")
                        .WithMany("Params")
                        .HasForeignKey("RuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rule");
                });

            modelBuilder.Entity("ThemarIP.Domain.Entities.Pfm.PfmLearningSuggestion", b =>
                {
                    b.HasOne("ThemarIP.Domain.Entities.Pfm.PfmCategory", "CurrentCategory")
                        .WithMany("SuggestionsAsCurrent")
                        .HasForeignKey("CurrentCategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ThemarIP.Domain.Entities.Pfm.PfmSubcategory", "CurrentSubcategory")
                        .WithMany("SuggestionsAsCurrent")
                        .HasForeignKey("CurrentSubcategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ThemarIP.Domain.Entities.Pfm.PfmCategorizationRule", "GeneratedRule")
                        .WithMany()
                        .HasForeignKey("GeneratedRuleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ThemarIP.Domain.Entities.Pfm.PfmCategory", "SuggestedCategory")
                        .WithMany("SuggestionsAsSuggested")
                        .HasForeignKey("SuggestedCategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ThemarIP.Domain.Entities.Pfm.PfmSubcategory", "SuggestedSubcategory")
                        .WithMany("SuggestionsAsSuggested")
                        .HasForeignKey("SuggestedSubcategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CurrentCategory");

                    b.Navigation("CurrentSubcategory");

                    b.Navigation("GeneratedRule");

                    b.Navigation("SuggestedCategory");

                    b.Navigation("SuggestedSubcategory");
                });

            modelBuilder.Entity("ThemarIP.Domain.Entities.Pfm.PfmMerchant", b =>
                {
                    b.HasOne("ThemarIP.Domain.Entities.Pfm.PfmCategory", "DefaultCategory")
                        .WithMany("MerchantsAsDefault")
                        .HasForeignKey("DefaultCategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ThemarIP.Domain.Entities.Pfm.PfmSubcategory", "DefaultSubcategory")
                        .WithMany("MerchantsAsDefault")
                        .HasForeignKey("DefaultSubcategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DefaultCategory");

                    b.Navigation("DefaultSubcategory");
                });

            modelBuilder.Entity("ThemarIP.Domain.Entities.Pfm.PfmMerchantAlias", b =>
                {
                    b.HasOne("ThemarIP.Domain.Entities.Pfm.PfmMerchant", "Merchant")
                        .WithMany("Aliases")
                        .HasForeignKey("MerchantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Merchant");
                });

            modelBuilder.Entity("ThemarIP.Domain.Entities.Pfm.PfmRuleCondition", b =>
                {
                    b.HasOne("ThemarIP.Domain.Entities.Pfm.PfmCategorizationRule", "Rule")
                        .WithMany("Conditions")
                        .HasForeignKey("RuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rule");
                });

            modelBuilder.Entity("ThemarIP.Domain.Entities.Pfm.PfmSubcategory", b =>
                {
                    b.HasOne("ThemarIP.Domain.Entities.Pfm.PfmCategory", "Category")
                        .WithMany("Subcategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ThemarIP.Domain.Entities.Pfm.PfmTransaction", b =>
                {
                    b.HasOne("ThemarIP.Domain.Entities.Pfm.PfmMerchant", "Merchant")
                        .WithMany("Transactions")
                        .HasForeignKey("MerchantId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ThemarIP.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Merchant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ThemarIP.Domain.Entities.Pfm.PfmTransactionCategory", b =>
                {
                    b.HasOne("ThemarIP.Domain.Entities.Pfm.PfmCategory", "Category")
                        .WithMany("TransactionCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ThemarIP.Domain.Entities.Pfm.PfmCategorizationRule", "MatchedRule")
                        .WithMany("TransactionCategories")
                        .HasForeignKey("MatchedRuleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ThemarIP.Domain.Entities.Pfm.PfmSubcategory", "Subcategory")
                        .WithMany("TransactionCategories")
                        .HasForeignKey("SubcategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ThemarIP.Domain.Entities.Pfm.PfmTransaction", "Transaction")
                        .WithOne("Category")
                        .HasForeignKey("ThemarIP.Domain.Entities.Pfm.PfmTransactionCategory", "TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("MatchedRule");

                    b.Navigation("Subcategory");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("ThemarIP.Domain.Entities.Pfm.PfmUserCorrection", b =>
                {
                    b.HasOne("ThemarIP.Domain.Entities.Pfm.PfmCategory", "CorrectedCategory")
                        .WithMany("CorrectedCategoryCorrections")
                        .HasForeignKey("CorrectedCategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ThemarIP.Domain.Entities.Pfm.PfmSubcategory", "CorrectedSubcategory")
                        .WithMany("CorrectedSubcategoryCorrections")
                        .HasForeignKey("CorrectedSubcategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ThemarIP.Domain.Entities.Pfm.PfmCategorizationRule", "GeneratedRule")
                        .WithMany()
                        .HasForeignKey("GeneratedRuleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ThemarIP.Domain.Entities.Pfm.PfmCategory", "OriginalCategory")
                        .WithMany("OriginalCategoryCorrections")
                        .HasForeignKey("OriginalCategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ThemarIP.Domain.Entities.Pfm.PfmSubcategory", "OriginalSubcategory")
                        .WithMany("OriginalSubcategoryCorrections")
                        .HasForeignKey("OriginalSubcategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ThemarIP.Domain.Entities.User", "ReviewedByAdmin")
                        .WithMany()
                        .HasForeignKey("ReviewedByAdminId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ThemarIP.Domain.Entities.Pfm.PfmTransaction", "Transaction")
                        .WithMany("Corrections")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ThemarIP.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CorrectedCategory");

                    b.Navigation("CorrectedSubcategory");

                    b.Navigation("GeneratedRule");

                    b.Navigation("OriginalCategory");

                    b.Navigation("OriginalSubcategory");

                    b.Navigation("ReviewedByAdmin");

                    b.Navigation("Transaction");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ThemarIP.Domain.Entities.StatementUpload", b =>
                {
                    b.HasOne("ThemarIP.Domain.Entities.User", "User")
                        .WithMany("StatementUploads")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ThemarIP.Domain.Entities.Subscription", b =>
                {
                    b.HasOne("ThemarIP.Domain.Entities.User", "User")
                        .WithMany("Subscriptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ThemarIP.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("ThemarIP.Domain.Entities.StatementUpload", "StatementUpload")
                        .WithMany("Transactions")
                        .HasForeignKey("StatementUploadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ThemarIP.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ThemarIP.Domain.Entities.User", null)
                        .WithMany("Transactions")
                        .HasForeignKey("UserId1");

                    b.Navigation("StatementUpload");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ThemarIP.Domain.Entities.Pfm.PfmCategorizationRule", b =>
                {
                    b.Navigation("Conditions");

                    b.Navigation("TransactionCategories");
                });

            modelBuilder.Entity("ThemarIP.Domain.Entities.Pfm.PfmCategory", b =>
                {
                    b.Navigation("CorrectedCategoryCorrections");

                    b.Navigation("MerchantsAsDefault");

                    b.Navigation("OriginalCategoryCorrections");

                    b.Navigation("Rules");

                    b.Navigation("Subcategories");

                    b.Navigation("SuggestionsAsCurrent");

                    b.Navigation("SuggestionsAsSuggested");

                    b.Navigation("TransactionCategories");
                });

            modelBuilder.Entity("ThemarIP.Domain.Entities.Pfm.PfmIntelligenceRule", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("Params");
                });

            modelBuilder.Entity("ThemarIP.Domain.Entities.Pfm.PfmMerchant", b =>
                {
                    b.Navigation("Aliases");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("ThemarIP.Domain.Entities.Pfm.PfmSubcategory", b =>
                {
                    b.Navigation("CorrectedSubcategoryCorrections");

                    b.Navigation("MerchantsAsDefault");

                    b.Navigation("OriginalSubcategoryCorrections");

                    b.Navigation("Rules");

                    b.Navigation("SuggestionsAsCurrent");

                    b.Navigation("SuggestionsAsSuggested");

                    b.Navigation("TransactionCategories");
                });

            modelBuilder.Entity("ThemarIP.Domain.Entities.Pfm.PfmTransaction", b =>
                {
                    b.Navigation("Category");

                    b.Navigation("Corrections");
                });

            modelBuilder.Entity("ThemarIP.Domain.Entities.StatementUpload", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("ThemarIP.Domain.Entities.User", b =>
                {
                    b.Navigation("AdminAuditLogs");

                    b.Navigation("AiQueries");

                    b.Navigation("KycSubmissions");

                    b.Navigation("StatementUploads");

                    b.Navigation("Subscriptions");

                    b.Navigation("TargetAuditLogs");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
